# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d99b85b8ade565ab034a7435d13c2aac03eb458caacad71901a2d27163f3cfe6a4e33e49a6eefab46193766dd5f680bfd3411bf47d032279b35971a5c6f2953c

test:
  secret_key_base: d89130063e4648f889e293d9b5923bc01ce1d4f65088121ba66603ad4325bae1aeb6a4a8b173c0526d81ea93522e2c18d5b0349d381e81f7aa97a83575b7498e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
